eclipse-tractusx/item-relationship-service

- .github/workflows/irs-build.yml
- README.md
- pom.xml
We now make use of the secret variable SONAR_ORGANIZATION to choose the right org to push the analysis to instead of hardcoding it.
> chore(migration):[TRI-797] Fix sonar analysis on eclipse project

- irs-api/pom.xml
The update to jackson-databind 2.14 leads to MethodNotFoundExceptions in tests.
> fix(dependencies)[-] Revert update of jackson-databind due to missing methods

- charts/irs-helm/CHANGELOG.md
- charts/irs-helm/Chart.yaml
- charts/irs-helm/templates/configmap-spring-app-config.yaml
This will add the missing config keys for the new ESS entries in the Spring configmap.
> chore(helm): Fix config syntax in spring configmap

- .github/workflows/kics.yml
Yo, yo, listen up, I got a tale to tell,
'Bout how our dev game is ringin' like a bell.
We're on this GitHub grind, pull requests in flight,
But when it comes to scans, man, somethin' ain't right.
Listen, y'all ambitious, that's cool, no debate,
But double, triple scans? Man, let's set this straight.
Veracode, Spotbugs, doing their dance,
But why we got all three for a single PR glance?
Here's my proposition, let's trim it lean,
Drop Veracode and Spotbugs, let CodeQL be the queen.
Security's important, that's the universal rule,
But PR after PR, we lookin' like a fool.
Secret Scan on the PR, that's all we need,
Let the rest run at night, let our main branch breathe.
So what y'all say? Time to make our move,
A bit of fun's essential when we're in the dev groove.
Open to suggestions, let's …
> chore: no secret scanning by KICS

- CHANGELOG.md
- charts/irs-helm/CHANGELOG.md
- irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/EdcControlPlaneClient.java
Add status "started" as acceptable state to complete the transfer process to fix #262
> Prepare IRS hotfix 4.0.1

- DEPENDENCIES
- pom.xml
Update irs registry client to 1.4.1
> Hotfix/release 23.12

- CONTRIBUTING.md
…rdcoded url
The code style settings reside in the repository. So a relative link is sufficient and more flexible than a hard coded URL.
> chore(docs): use a relative link to code style settings

- .github/workflows/helm-test.yaml
- CHANGELOG.md
- Dockerfile
- charts/irs-helm/CHANGELOG.md
- Remove `apk upgrade --no-cache libssl3 libcrypto3` to fix #294
> fix(build): Remove apk upgrade to be TRG 4.02 compliant

- .gitignore
- CHANGELOG.md
- docs/build-docs-locally.sh
- Helper script for generating the documentation locally in WSL. The commands are copied from .github/workflows/publish-documentation.yaml but with this script the documentation can be build and tested locally before pushing to github. 
> chore(docs):[#xxx] Helper script for building docs locally

- .github/workflows/irs-build.yml
- DOCKER_NOTICE.md
- README.md
- Moved Docker Notice to dedicated File `DOCKER_NOTICE.md`
- Adjusted docker image publishing to include only this docker notice file
> chore(foss):[#425] Extract Docker notice to separate file

- irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/asset/EdcAssetService.java
- irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/policy/service/EdcPolicyDefinitionService.java
- irs-edc-client/src/test/java/org/eclipse/tractusx/irs/edc/client/asset/EdcAssetServiceTest.java
- irs-edc-client/src/test/java/org/eclipse/tractusx/irs/edc/client/policy/service/EdcPolicyDefinitionServiceTest.java
Fix recent asset creation service to send Strng and not JsonObject since JsonObject is not properly handled by deserialization of restTemplate
> feature(irs-edc-client): #412 fix asset creation in irs lib

- irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/contract/service/EdcContractAgreementService.java
- irs-edc-client/src/test/java/org/eclipse/tractusx/irs/edc/client/contract/service/EdcContractAgreementServiceTest.java
add authentication header to EdcContractAgreementService
> feature: 420 add headers to EdcContractAgreementService

- irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/contract/model/EdcContractAgreementRequest.java
- irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/contract/service/EdcContractAgreementService.java
- fix filterExpression for contract agreements
> feature: 420 fix filterExpression

- DEPENDENCIES
- pom.xml
- Update registry client lib to release version 2.5.0
> chore(registry-client): Update registry client lib to 2.5.0

- local/testing/api-tests/irs-api-tests.tavern.yaml
- local/testing/api-tests/tavern_helpers.py
> chore(tavern):[#503] fix failing ess tests

- .github/workflows/dependencies-update.yaml
- CONTRIBUTING.md
> chore(workflows):[#371] fix missing profile for dependencies file check

- DEPENDENCIES
- pom.xml
This PR updates xmlunit-core from 2.9.1 to 2.10.0 .
> Chore: Update dependency

- .github/workflows/trivy-image-scan.yml
- CHANGELOG.md
see https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/949/files
- Fix Trivy workflow to fail only on CRITICAL, HIGH according to https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/949/files (as it was mentioned in the Community Office Hour 2024-06-28)
> chore(trivy):[#xxx] trivy fix mentioned in the Community Office Hour

- CHANGELOG.md
- charts/irs-helm/templates/configmap-spring-app-config.yaml
- charts/irs-helm/values.yaml
- irs-api/pom.xml
- irs-api/src/main/java/org/eclipse/tractusx/irs/services/validation/JsonValidatorService.java
- irs-api/src/main/resources/application.yml
- irs-api/src/test/java/org/eclipse/tractusx/irs/WiremockSupport.java
- irs-api/src/test/java/org/eclipse/tractusx/irs/services/validation/JsonValidatorServiceTest.java
- irs-api/src/test/resources/__files/assemblyPartRelationship.json
- irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/EdcConfiguration.java
- irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/EdcSubmodelFacade.java
- irs-edc-client/src/test/java/org/eclipse/tractusx/irs/edc/client/EdcSubmodelFacadeTest.java
- irs-edc-client/src/test/java/org/eclipse/tractusx/irs/edc/client/SubmodelRetryerTest.java
- irs-registry-client/src/main/java/org/eclipse/tractusx/irs/registryclient/DefaultConfiguration.java
- irs-registry-client/src/test/java/org/eclipse/tractusx/irs/registryclient/DefaultConfigurationTest.java
- pom.xml
fix(edc-client): Add property "submodel-postfix" to be prefixed for submodel call for IRS version 4.5.2
Task : https://github.com/eclipse-tractusx/item-relationship-service/issues/739
Added $Value to submodel URL for IRS version 4.5.2 and updated submodel URL to hotfix tracex
> IRS-739_add_value_for_submodel_url_for_IRS_version_4.5.2

- charts/item-relationship-service/CHANGELOG.md
- charts/item-relationship-service/Chart.yaml
- Updated bitnami/common helm dependency to 2.x.x to match other charts of the umbrella chart
> chore(charts): update bitnami/common to 2.x.x

- irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/RelationshipDelegate.java
- irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/SubmodelDelegate.java
- irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/exceptions/PolicyException.java
- irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/exceptions/UsagePolicyExpiredException.java
- irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/exceptions/UsagePolicyPermissionException.java
> feature: eclipse-tractusx/traceability-foss#639 add catch clause

- CHANGELOG.md
- irs-policy-store/src/main/java/org/eclipse/tractusx/irs/policystore/services/PolicyStoreService.java
- irs-policy-store/src/test/java/org/eclipse/tractusx/irs/policystore/services/PolicyStoreServiceTest.java
> fix(policy-validation):[#757] fix

- .tractusx
This PR addresses the new state of TRG 1.08.
- Added property in `.tractusx` metadata file to reference OpenAPI spec since the spec does not reside in the path `/docs/api` required by TRG 1.08
> chore(trg): update .tractusx metadata file for TRG 1.08

- CHANGELOG.md
- docs/src/api/irs-api.yaml
- irs-policy-store/src/main/java/org/eclipse/tractusx/irs/policystore/controllers/PolicyStoreController.java
- harmonize description of GET /irs/policies and /irs/policies/paged
- describe supported attributes in filter and sort
- document supported search operators and value format
- document default and max page size
- improve documentation for #639, see comment https://github.com/eclipse-tractusx/item-relationship-service/issues/639#issuecomment-2238803508
> chore(documentation): [#639] improve documentation

- docs/src/api/irs-api.yaml
- irs-policy-store/src/main/java/org/eclipse/tractusx/irs/policystore/controllers/PolicyStoreController.java
- deprecation note for `GET /irs/policies` (in future the paged endpoint should be used), see #639
> chore(documentation): [#639] deprecation note for `GET /irs/policies`

- .github/workflows/cucumber-integration-test-INT-association.yaml
> chore(workflows):[#828] fix secret names and executionFilter

- FAQ.md
- extend FAQ with troubleshooting questions #824
> chore(docs):[#824] extend faq with troubleshooting questions

- .github/workflows/cucumber-integration-test-UMBRELLA.yaml
- .github/workflows/release.yaml
- .github/workflows/tavern-UMBRELLA.yml
- replace hardcoded GH repo URL with variables
- choose GH runner for umbrella tests dynamically, depending on the repo
> chore(workflows): replace hardcoded GH repo URL with variables

- docs/src/uml-diagrams/runtime-view/scaling-edc-processing.puml
- docs/src/uml-diagrams/runtime-view/scaling-job-batch-processing.puml
- docs/src/uml-diagrams/runtime-view/scaling-job-processing.puml
Added 3 sequence diagrams to illustrate points of improvements in the IRS Job process in regards to scalability.
They focus on internal IRS processes, as well as communication with the Digitial Twin Registry (DTR) and Eclipse Dataspace Connector (EDC).
> chore(docs): add sequence diagrams for improvements in scalability

- CHANGELOG.md
- charts/item-relationship-service/CHANGELOG.md
- charts/item-relationship-service/templates/configmap-spring-app-config.yaml
- charts/item-relationship-service/values.yaml
- irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/RegistryConfiguration.java
- irs-registry-client/src/main/java/org/eclipse/tractusx/irs/registryclient/DefaultConfiguration.java
- irs-registry-client/src/main/java/org/eclipse/tractusx/irs/registryclient/discovery/ConnectorEndpointsService.java
- irs-registry-client/src/test/java/org/eclipse/tractusx/irs/registryclient/DefaultConfigurationTest.java
- irs-registry-client/src/test/java/org/eclipse/tractusx/irs/registryclient/decentral/DecentralDigitalTwinRegistryServiceWiremockTest.java
- irs-registry-client/src/test/java/org/eclipse/tractusx/irs/registryclient/discovery/ConnectorEndpointsServiceTest.java
- irs-registry-client/src/test/java/org/eclipse/tractusx/irs/registryclient/discovery/DiscoveryFinderClientImplTest.java
- local/deployment/full-irs/subcharts/discovery/templates/configmap.yaml
The EDC discovery flow to be changed from type “bpn” to “bpnl”, and this parameter to be configurable in the future.
The EDC discovery flow works in the Cofinity-X system environment and could be easily adapted in the future.
- Made the discovery type configurable, with a default value of bpnl for both Traceability and IRS.
> chore: [TRX-96] Adapt-Discovery-flow (bpnl) (#12)
