eclipse-tractusx/item-relationship-service

.github/workflows/eclipse-dash.yml, DEPENDENCIES
This needs to be up-to-date, especially with the Spring Boot update now.
=> chore(licenses):[-] Update license overview in DEPENDENCIES file

.tractusx
https://eclipse-tractusx.github.io/docs/release/trg-0/trg-0-repository-metafile
=> Create metadatafile for Tractus-X projects

README.md
Recommended update of some bullet points to your readme contents on - Notice for Docker Image section.
As I am not able to assign revieweres @ds-jkreutzfeld could you please have a look at it.
=> doc(readme): Updated bullet points for better readability.

irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/local/LocalTestDataConfiguration.java
be able to start the irs by running:
java -Dspring.profiles.active=local -jar irs-api/target/irs-api-0.0.2-SNAPSHOT-exec.jar
=> feat(run):[TRI-XXX] Changes to optionally run the app without the run configuration

CODE_OF_CONDUCT.md
Updated the community code of conduct to latest version 2.0 https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php
=> chore(community): Update code of conduct to version 2.0

.github/workflows/gpghelper.sh, .github/workflows/maven-deploy.yaml, DEPENDENCIES, irs-api/pom.xml, irs-registry-client/pom.xml, pom.xml
It now signs and pushes correctly to the Sonatype repository.
=> Fix the maven deployment pipeline for the DTR library

.github/workflows/maven-deploy.yaml
Use correct version variable in SNAPSHOT comparison
=> fix(workflow):[-] Use correct variable in workflow

.github/ISSUE_TEMPLATE/irs-story
I want to add a issue template for an IRS - Story to manage the Project in Github Projects.
=> Create irs-story issue template

CHANGELOG.md, charts/irs-helm/CHANGELOG.md
- Prepared changelog for release 4.5.1
=> chore(docs):[#425] Add changelog for release 4.5.1

CHANGELOG.md, charts/irs-helm/CHANGELOG.md, charts/irs-helm/Chart.yaml, docs/src/api/irs-api.yaml, irs-api/src/main/java/org/eclipse/tractusx/irs/IrsApplication.java
- Update IRS OpenAPI version to 4.5.2
- Add release notes for hotfix release 4.5.2
=> chore(irs-api): Update IRS OpenAPI version to 4.5.2

irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/contract/service/EdcContractAgreementService.java, irs-edc-client/src/test/java/org/eclipse/tractusx/irs/edc/client/contract/service/EdcContractAgreementServiceTest.java
- fixed the base URL in EdcContractAgreementService
=> feature: 420 fix base url in EdcContractAgreementService

irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/contract/service/EdcContractAgreementService.java
- fix RestTemplate not found issue
=> feature: 420 fix bean discovery

irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/contract/model/EdcContractAgreementsResponse.java, irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/contract/service/EdcContractAgreementService.java, irs-edc-client/src/test/java/org/eclipse/tractusx/irs/edc/client/contract/model/EdcContractAgreementsResponseTest.java, irs-edc-client/src/test/java/org/eclipse/tractusx/irs/edc/client/contract/service/EdcContractAgreementServiceTest.java
- rework EdcContractAgreementsResponse
=> feature: 420 rework EdcContractAgreementsResponse

CHANGELOG.md, COMPATIBILITY_MATRIX.md, charts/irs-helm/CHANGELOG.md
- Add new version to CHANGELOG, helm chart CHANGELOG and 
- Updated COMPATIBILITY_MATRIX with new version
=> docs(release): Prepare release 4.7.0

irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/contract/model/EdcContractAgreementNegotiationResponse.java
- refactor EdcContractAgreementNegotiationResponse
=> feature: 420 refactor EdcContractAgreementNegotiationResponse.java

irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/contract/model/EdcContractAgreementsResponse.java, irs-edc-client/src/test/java/org/eclipse/tractusx/irs/edc/client/contract/service/EdcContractAgreementServiceTest.java
=> feature: 420 add policy to request

local/testing/testdata/transform-and-upload.py
- Added new parameter `--edcBPN` to test data upload script #358
=> chore(testing):[#358] fix data upload script

local/testing/request-collection/IRS_Request_Collection.json
=> feat(impl):[#568] remove insomnia bpn loookup

CHANGELOG.md, charts/item-relationship-service/CHANGELOG.md, charts/item-relationship-service/Chart.yaml, docs/src/api/irs-api.yaml, irs-api/src/main/java/org/eclipse/tractusx/irs/IrsApplication.java
=> chore(docs): Pull in changes from hotfix 5.1.2

charts/item-relationship-service/values.yaml
=> feat(impl):[#619] default pull policy adjutment

CHANGELOG.md, DEPENDENCIES, irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/contract/model/EdcContractAgreementNegotiationResponse.java, irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/contract/model/EdcContractAgreementsResponse.java, pom.xml
fixes eclipse-tractusx/traceability-foss#963
=> Bug/963 fix contract agreements in edc version 0.7.0

CHANGELOG.md, irs-api/src/main/java/org/eclipse/tractusx/irs/ess/service/EssService.java, irs-api/src/test/java/org/eclipse/tractusx/irs/ess/service/EssServiceTest.java
=> feat(impl):[#579] adjust aspect types ess request body

COMPATIBILITY_MATRIX.md
- add latest releases to compatibility matrix
=> chore(docs): add latest releases to compatibility matrix

irs-cucumber-tests/src/test/resources/expected-files/TRI-2035-expected-tombstones.json
- add expected tombstone file for test TRI-2035 #595
=> chore(tavern):[#595] add expected tombstone file

local/testing/api-tests/tavern_helpers.py
- added missing assert for ESS tombstone validation
=> chore(tavern):[#503] fix tavern ess assert

local/testing/api-tests/irs-api-tests.tavern.yaml
=> chore(tavern):[#503] fixing aspects in ess test

docs/concept/#529-E2E-tests-aspect-version-compatibility/#529-E2E-tests-aspect-version-compatibility.md
- fix documentation in context of #529 (wrong path, removed superfluous links)
=> chore(test):[#529] fix SingleLevelBomAsBuilt test documentation

docs/concept/#529-E2E-tests-aspect-version-compatibility/#529-E2E-tests-aspect-version-compatibility.md
=> chore(concept):[#529] Add description for futureAddedField in concept

.github/workflows/cucumber-integration-test.yaml, irs-cucumber-tests/src/test/java/org/eclipse/tractusx/irs/cucumber/RunCucumberTest.java, pom.xml
=> chore(workflows):[#371] add workaround cucumber report token replacement

DEPENDENCIES, pom.xml
=> chore(deps): update registry client lib to 2.1.1

.github/workflows/cucumber-integration-test-DIL.yaml, .github/workflows/cucumber-integration-test-INT.yaml, .github/workflows/cucumber-integration-test.yaml, .github/workflows/int-setup-testdata.yml, .github/workflows/int-test-automation.yml, .github/workflows/integration-test-DEV.yaml, .github/workflows/irs-build.yml, .github/workflows/irs-load-test.yaml, .github/workflows/owasp.yml, TESTS.md
Reverts eclipse-tractusx/item-relationship-service#735
=> Revert "Chore/222 adopt tractusx as main repo"

docs/src/docs/arc42/cross-cutting/safety-security.adoc
- Update Rights and Roles Matrix of IRS for #639 
=> chore(documentation):[#639] Rights and Roles Matrix of IRS updated

pom.xml
- update spring boot to 3.1.12
=> chore(depedencies):[#xxx] update spring boot to 3.1.12

DEPENDENCIES, irs-parent-spring-boot/pom.xml
- update tomcat-embed-core in order to fix trivy HIGH warning
=> chore(dependencies):[#xxx] update tomcat-embed-core

COMPATIBILITY_MATRIX.md
=> chore(docs): update Compatibility Matrix

irs-api/src/test/java/org/eclipse/tractusx/irs/IrsWireMockIntegrationTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/component/TombstoneTest.java, irs-models/pom.xml, irs-models/src/main/java/org/eclipse/tractusx/irs/component/Tombstone.java
=> fix(irs-api):[#538] add deep search for exception cause

COMPATIBILITY_MATRIX.md
=> chore(docs): update compatibility matrix for latest CX Release version

CHANGELOG.md, irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/job/CallbackResponderEventListener.java, irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/job/CallbackResponderEventListenerTest.java
=> feat(irs-api): allow local urls for irs callbacks

charts/connector/aasregistry/Chart.yaml
=> chore(charts): update registry to R24.08 version 0.5.2

CONTACT.md
=> Add icc email contact

CHANGELOG.md, irs-api/src/test/java/org/eclipse/tractusx/irs/connector/job/InMemoryJobStoreTest.java
- fix flaky test (discovered in context of #841)
=> chore(test): [#xxx] Fix flaky test

irs-cucumber-tests/src/test/resources/expected-files/TRI-2035-expected-tombstones.json, irs-models/src/main/java/org/eclipse/tractusx/irs/component/Tombstone.java
=> fix(irs-models): fix missing expected tombstone data

.github/workflows/irs-build.yml
- add permissions to workflow call
=> chore(workflows): add permissions to workflow call

CHANGELOG.md, irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/asset/EdcAssetService.java, irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/model/EdcTechnicalServiceAuthentication.java, irs-edc-client/src/test/java/org/eclipse/tractusx/irs/edc/client/asset/EdcAssetServiceTest.java
Extended the notification contract creation by an optional api key for secured access of edc dataplane to callback api.
=> chore: [TRX-105] secure edc callbacks (#19)

CHANGELOG.md, charts/item-relationship-service/templates/configmap-spring-app-config.yaml, charts/item-relationship-service/values-umbrella.yaml, charts/item-relationship-service/values.yaml, irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/JobConfiguration.java, irs-api/src/main/java/org/eclipse/tractusx/irs/services/BatchOrderEventListener.java, irs-api/src/main/java/org/eclipse/tractusx/irs/services/ExecutorCompletionServiceFactory.java, irs-api/src/main/resources/application.yml, irs-api/src/test/java/org/eclipse/tractusx/irs/IrsWireMockIntegrationTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/WiremockSupport.java, irs-api/src/test/java/org/eclipse/tractusx/irs/services/BatchOrderEventListenerTest.java, irs-registry-client/src/main/java/org/eclipse/tractusx/irs/registryclient/decentral/DecentralDigitalTwinRegistryService.java
https://github.com/eclipse-tractusx/item-relationship-service/issues/892
=> feat: parallel processing of batch order jobs

charts/item-relationship-service/values.yaml, local/deployment/full-irs/Chart.yaml, local/deployment/full-irs/README.md, local/deployment/full-irs/subcharts/edc-control-plane/Chart.yaml, local/deployment/full-irs/subcharts/edc-control-plane/values.yaml, local/deployment/full-irs/subcharts/edc-data-plane/Chart.yaml, local/deployment/full-irs/subcharts/edc-data-plane/values.yaml, local/deployment/full-irs/subcharts/irs-frontend-service/Chart.yaml, local/deployment/full-irs/subcharts/irs-frontend-service/values.yaml, local/deployment/full-irs/subcharts/irs-provider-backend/values.yaml, local/deployment/full-irs/test/edc-consumer-data-plane.rest, local/deployment/full-irs/values-dev.yaml, local/deployment/full-irs/values.yaml
Removed some references to catenaX-ng and marked certain occurrences for review where I was unsure.
Closes #876 
=> chore: removed some catenaX-ng references and marked some occurrences for review

COMPATIBILITY_MATRIX.md, charts/item-relationship-service/CHANGELOG.md
Added compatibility matrix for release 6.0.0
=> chore(docs): update COMPATIBILITY_MATRIX.md

CHANGELOG.md, irs-api/src/main/resources/application.yml
=> fix(irs-api): add missing discovery type config

.github/workflows/dependencies-update.yaml, .github/workflows/update-registry-library.yaml
- add workflow permission `contents: write` to workflows where PRs are created
=> chore(workflows): fix workflow permissions

pom.xml
=> chore: Upgrade irs-registry-client.

.github/actions/cucumber-integration-test/action.yaml, CHANGELOG.md, COMPATIBILITY_MATRIX.md, charts/item-relationship-service/CHANGELOG.md, irs-api/pom.xml, irs-common/pom.xml, irs-cucumber-tests/pom.xml, irs-integration-tests/pom.xml, irs-registry-client/pom.xml, irs-testing/pom.xml, pom.xml
As Developers we want to guarantee a safe and maintained repository according to the Tractus-X Release Guildelines and update all dependencies. #951 
=> fix: 951 upgrade versions and exclude vulnerable artifacts

pom.xml
Bump IRS Client Version to 3.0.2
#951 
=> fix: 951 bump client libraries

.github/actions/setup-umbrella-env/action.yaml
fix: correct ref for Checkout umbrella Charts
=> fix: correct ref for wf step "Checkout umbrella Charts"

CHANGELOG.md, irs-api/pom.xml, irs-edc-client/pom.xml, pom.xml
Needed dependency change to provide a secure software.
=> chore: Update irs-registry-client, and fix cve in common utils.
